# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm install --force
    - name: Run Tests
      env:
        BROWSERSTACK_USER: ${{secrets.BROWSERSTACK_USER}}
        BROWSERSTACK_API_KEY: ${{secrets.BROWSERSTACK_API_KEY}}
        TESTING_PLATFORM: ${{secrets.TESTING_PLATFORM}}
        BROWSERSTACK_APP_LINK: ${{secrets.BROWSERSTACK_APP_LINK}}
      run: npx wdio
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: logs
        path: logs
